# Generated by Django 3.1 on 2021-08-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='weather_date',
        ),
    ]
